HEADER_LENGTH = 30
MAX_AMOUNT_LENGTH = 7
MAX_DESCRIPTION_LENGTH = 23
TWO_DECIMAL_FORMAT = "%.2f"

SPEND_CHART_TITLE = "Percentage spent by category"
Y_LABEL_MAX = 100
Y_LABEL_MIN = 0
Y_LABEL_INCREMENT = 10
Y_LABEL_SPACE = 3
Y_LABEL_PLUS_AXIS_SPACE = 4
BAR_WIDTH = 3